#!/usr/bin/env python3
"""
GENERATED BY CLAUDE
LeetCode Random Problem Fetcher
Emails a random problem from LeetCode daily at midnight within a specified difficulty range.
"""

import requests
import random
import time
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime, timedelta

def fetch_problems(difficulty=""):
    """Fetch all problems from LeetCode API with optional difficulty filter."""
    print(f"Fetching LeetCode problems{f' (difficulty: {difficulty})' if difficulty else ''}...")
    
    try:
        # Using alfa-leetcode-api
        url = "https://alfa-leetcode-api.onrender.com/problems"
        if difficulty:
            url += f"?difficulty={difficulty.upper()}"
        
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()
        
        if 'problemsetQuestionList' not in data:
            print("Error: Unexpected API response format")
            return []
        
        problems = data['problemsetQuestionList']
        print(f"Found {len(problems)} problems.")
        return problems
        
    except requests.RequestException as e:
        print(f"Error fetching problems: {e}")
        return []

def send_test_email(recipient_email, smtp_server, smtp_port, sender_email, sender_password):
    """Send a test email to verify configuration."""
    # Create email
    msg = MIMEMultipart('alternative')
    msg['Subject'] = "🚀 LeetCode Problem Emailer - Test Email"
    msg['From'] = sender_email
    msg['To'] = recipient_email
    
    # Plain text version
    text = f"""
LeetCode Problem Emailer - Test Email
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

Starting Script...

Your daily LeetCode problem emailer is now active!
You will receive a random problem every day at midnight (12:00 AM).

If you're seeing this email, your configuration is working correctly! ✅

Happy coding!
"""
    
    # HTML version
    html = f"""
    <html>
      <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: linear-gradient(135deg, #FFA116 0%, #FF6B00 100%); padding: 20px; border-radius: 10px 10px 0 0;">
          <h2 style="color: white; margin: 0;">🚀 LeetCode Problem Emailer</h2>
          <p style="color: #fff3e0; margin: 5px 0 0 0;">Test Email</p>
        </div>
        <div style="background: #f5f5f5; padding: 20px; border-radius: 0 0 10px 10px;">
          <h3 style="color: #333; margin-top: 0;">Starting Script...</h3>
          <p style="color: #666;">Your daily LeetCode problem emailer is now active!</p>
          <p style="color: #666;">You will receive a random problem every day at <strong>midnight (12:00 AM)</strong>.</p>
          <div style="background: #e8f5e9; border-left: 4px solid #4caf50; padding: 12px; margin: 15px 0; border-radius: 4px;">
            <p style="color: #2e7d32; margin: 0;">✅ If you're seeing this email, your configuration is working correctly!</p>
          </div>
          <p style="color: #999; font-size: 12px; margin-top: 20px;">Happy coding! 💻</p>
          <p style="color: #bbb; font-size: 11px; margin-top: 10px;">{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </div>
      </body>
    </html>
    """
    
    msg.attach(MIMEText(text, 'plain'))
    msg.attach(MIMEText(html, 'html'))
    
    try:
        # Send email
        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.send_message(msg)
        return True
    except Exception as e:
        print(f"❌ Error sending test email: {e}")
        return False

def send_email(problem, recipient_email, smtp_server, smtp_port, sender_email, sender_password):
    """Send problem via email."""
    title = problem.get('title', 'Unknown')
    title_slug = problem.get('titleSlug', '')
    difficulty = problem.get('difficulty', 'Unknown')
    link = f"https://leetcode.com/problems/{title_slug}/"
    
    # Get topic tags
    tags = [tag['name'] for tag in problem.get('topicTags', [])]
    tags_str = ', '.join(tags) if tags else 'None'
    
    # Create email
    msg = MIMEMultipart('alternative')
    msg['Subject'] = f"🎯 Daily LeetCode Problem - {title}"
    msg['From'] = sender_email
    msg['To'] = recipient_email
    
    # Difficulty color mapping
    difficulty_colors = {
        'Easy': '#00b8a3',
        'Medium': '#ffc01e',
        'Hard': '#ef4743'
    }
    color = difficulty_colors.get(difficulty, '#667eea')
    
    # Plain text version
    text = f"""
Daily LeetCode Problem
{datetime.now().strftime('%Y-%m-%d')}

Problem: {title}
Difficulty: {difficulty}
Topics: {tags_str}

Solve it here: {link}

Happy coding!
"""
    
    # HTML version
    html = f"""
    <html>
      <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: linear-gradient(135deg, #FFA116 0%, #FF6B00 100%); padding: 20px; border-radius: 10px 10px 0 0;">
          <h2 style="color: white; margin: 0;">🎯 Daily LeetCode Problem</h2>
          <p style="color: #fff3e0; margin: 5px 0 0 0;">{datetime.now().strftime('%B %d, %Y')}</p>
        </div>
        <div style="background: #f5f5f5; padding: 20px; border-radius: 0 0 10px 10px;">
          <h3 style="color: #333; margin-top: 0;">{title}</h3>
          <p style="color: #666;"><strong>Difficulty:</strong> <span style="color: {color}; font-weight: bold;">{difficulty}</span></p>
          <p style="color: #666;"><strong>Topics:</strong> {tags_str}</p>
          <a href="{link}" style="display: inline-block; background: #FFA116; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; margin-top: 10px;">Solve Problem</a>
          <p style="color: #999; font-size: 12px; margin-top: 20px;">Happy coding! 💻</p>
        </div>
      </body>
    </html>
    """
    
    msg.attach(MIMEText(text, 'plain'))
    msg.attach(MIMEText(html, 'html'))
    
    try:
        # Send email
        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.send_message(msg)
        print(f"✅ Email sent successfully to {recipient_email}")
        return True
    except Exception as e:
        print(f"❌ Error sending email: {e}")
        return False

def display_problem(problem):
    """Display problem information in a formatted way."""
    title = problem.get('title', 'Unknown')
    title_slug = problem.get('titleSlug', '')
    difficulty = problem.get('difficulty', 'Unknown')
    tags = [tag['name'] for tag in problem.get('topicTags', [])]
    tags_str = ', '.join(tags) if tags else 'None'
    
    print("\n" + "="*60)
    print(f"🎯 RANDOM LEETCODE PROBLEM")
    print(f"📅 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("="*60)
    print(f"Problem: {title}")
    print(f"Difficulty: {difficulty}")
    print(f"Topics: {tags_str}")
    print(f"Link: https://leetcode.com/problems/{title_slug}/")
    print("="*60 + "\n")

def get_seconds_until_midnight():
    """Calculate seconds until next midnight."""
    now = datetime.now()
    tomorrow = now + timedelta(days=1)
    midnight = datetime(tomorrow.year, tomorrow.month, tomorrow.day, 0, 0, 0)
    return (midnight - now).total_seconds()

def main():
    """Main function to run the daily problem fetcher."""
    print("LeetCode Random Problem Emailer")
    print("="*60)
    
    # Get email configuration
    print("\nEmail Configuration:")
    recipient_email = input("Enter your email address: ")
    sender_email = input("Enter sender email (e.g., your Gmail): ")
    sender_password = input("Enter sender email password/app password: ")
    
    # SMTP configuration (default for Gmail)
    use_gmail = input("Using Gmail? (y/n, default y): ").lower() or 'y'
    if use_gmail == 'y':
        smtp_server = "smtp.gmail.com"
        smtp_port = 587
        print("\n⚠️  Note: For Gmail, use an App Password, not your regular password.")
        print("Generate one at: https://myaccount.google.com/apppasswords")
    else:
        smtp_server = input("Enter SMTP server (e.g., smtp.gmail.com): ")
        smtp_port = int(input("Enter SMTP port (default 587): ") or "587")
    
    # Get difficulty preference
    print("\nDifficulty Selection:")
    print("1. Easy")
    print("2. Medium")
    print("3. Hard")
    print("4. All (random from any difficulty)")
    
    choice = input("Choose difficulty (1-4, default 4): ").strip() or "4"
    difficulty_map = {
        "1": "EASY",
        "2": "MEDIUM", 
        "3": "HARD",
        "4": ""
    }
    difficulty = difficulty_map.get(choice, "")
    
    print(f"\nStarting daily problem emailer (Difficulty: {difficulty if difficulty else 'All'})")
    print("Problems will be emailed at midnight (12:00 AM)")
    print("Press Ctrl+C to stop\n")
    
    # Fetch problems once at start
    problems = fetch_problems(difficulty)
    
    if not problems:
        print("No problems found. Exiting.")
        return
    
    # Send test email immediately
    print("Sending test email...")
    
    if send_test_email(recipient_email, smtp_server, smtp_port, sender_email, sender_password):
        print("✅ Test email sent successfully! Check your inbox.")
        print("If you didn't receive it, check your spam folder or verify your settings.\n")
    else:
        print("❌ Test email failed. Please check your settings and try again.")
        retry = input("Do you want to continue anyway? (y/n): ").lower()
        if retry != 'y':
            print("Exiting...")
            return
    
    try:
        # Display first problem immediately if starting close to midnight
        # Otherwise wait until midnight
        now = datetime.now()
        if now.hour == 0 and now.minute < 5:
            problem = random.choice(problems)
            display_problem(problem)
            send_email(problem, recipient_email, smtp_server, smtp_port, sender_email, sender_password)
        
        while True:
            # Calculate time until next midnight
            wait_time = get_seconds_until_midnight()
            hours = int(wait_time // 3600)
            minutes = int((wait_time % 3600) // 60)
            
            print(f"Next problem at midnight (in {hours}h {minutes}m)...")
            time.sleep(wait_time)
            
            # Display and email a random problem at midnight
            problem = random.choice(problems)
            display_problem(problem)
            send_email(problem, recipient_email, smtp_server, smtp_port, sender_email, sender_password)
            
    except KeyboardInterrupt:
        print("\n\nStopping problem emailer. Goodbye!")

if __name__ == "__main__":
    main()
